---

- name: téléchargement de logstash
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-{{elk_version}}-x86_64.rpm
    dest: /opt/logstash-{{elk_version}}.rpm
    mode: 0440
  register: logstash_dl
  when: parefeu_open is succeeded

- name: installation de logstash
  dnf:
    name: /opt/logstash-{{elk_version}}.rpm
    state: present
  register: logstash_instalation
  when: logstash_dl is succeeded

- name: activer le service
  shell: systemctl enable logstash --now
  when: logstash_dl is succeeded