---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-conf
  namespace: elk
  labels:
    name: kibana-conf
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch-service.elk.svc:9200" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
