---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-storage
  namespace: elk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi