---
  # tasks pour toutes les machines

- name: Update 
  become: true
  dnf:
    name: "*"
    state: latest

- name: instalation ifconfig
  become: true
  dnf:
    name: net-tools
    state: latest

- name: instalation du JDK
  become: true
  dnf:
    name: java-11-openjdk-headless
    state: latest