---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alert-manager-storage
  namespace: grafana-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi