---
- name: "deployer Elastique"
  hosts: elastic
  roles:
    - Commun
    - elasticsearch

- name: deployer dashboards
  hosts: kibana
  roles: 
    - Commun
    - Kibana
    - grafana

- name: deployer logstash
  hosts: logstash
  roles:
    - Commun
    - Logstash
      