---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana-prometheus
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.grafana-prometheus.svc:9090",
                "version": 1
            },
            {
               "access":"proxy",
                "editable": true,
                "name": "Elasticsearch",
                "orgId": 1,
                "type": "elasticsearch",
                "url": "http://elasticsearch-service.elk.svc:9200",
                "version": 1
            }
        ]
    }
#url -> http://<ServiceName>.<namespace>.svc:<port>